name: Issue Opend

on:
  issues:
    types: [opened]

jobs:
  issue-opend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue title
        if: github.event.issue.title == '🤔' || github.event.issue.title == '🙏' || github.event.issue.title == '🐛'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }}，请编辑你的 issue 标题, 一个言简意赅的 issue 标题可以节省大家的时间, 请不要将标题当做正文, 或者为空。

            Hello, @${{ github.event.issue.user.login }}, please edit your issue title. a concise issue title will save everyone time. please do not leave the title as the body or empty.

      # 标题或正文 (版本号) 带有 next, 增加标记便于统计
      - name: Auto Set Next Label
        if: contains(github.event.issue.title, 'next') || contains(github.event.issue.body, 'next')
        uses: actions-cool/issues-helper@main
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'next'

      - name: Auto Tips
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }}:
            
            ## 🌟 我们需要你的支持！
  
            **AntV/S2** 的成长离不开社区的力量，期待您用以下方式与我们同行：
  
            ### 1. 点亮星星标记 ✨
            
            如果 S2 为您的项目创造价值，请为我们点亮 GitHub Star！
              这个简单的动作将：
            - 提升项目在开源生态的可见度
            - 激励维护团队持续优化
            - 吸引更多开发者参与共建
              
            [⭐ 立即点亮 Star](https://github.com/antvis/S2)
              
            ### 2. 加入用户荣誉墙 🏆
            
            我们正在建立「S2 用户案例」展示墙，欢迎留下公司或产品名，您的回复将成为维护者、社区用户和观望者的信心来源 💪🏻 
              
            [📝 登记使用案例](https://github.com/antvis/S2/issues/903)
              
            ### 提 Issue 须知

            ⚠️ 在提出问题前，请确保你已经仔细阅读👓/搜索🔍过 [官方文档](https://s2.antv.antgroup.com) 和 [常见问题](https://s2.antv.antgroup.com/manual/faq) 以及 [图表示例](https://s2.antv.antgroup.com/examples), 并且已经搜索查阅过相关 [Issues 列表](https://github.com/antvis/S2/issues?q=is%3Aissue+is%3Aclosed) 和 [Discussions 列表](https://github.com/antvis/S2/discussions). 当你确定自己的问题没有解决方案时，请提交 issue。 ⚠️

            如果是使用问题，不知道怎么用，移步 [Discussions 讨论区](https://github.com/antvis/S2/discussions) 并提供 [有效信息](https://zhuanlan.zhihu.com/p/25795393) 进行 [提问](https://github.com/antvis/S2/discussions/new?category=q-a)。

            ### 参与社区共建

            **这是一个开源项目, 我们也有繁忙的业务要做, 是用自己的业余时间在维护, 为爱发电, 精力有限, 所以有时候 issue 响应速度不是那么及时, 如果你遇到了问题, 或者对 [Issues](https://github.com/antvis/S2/issues) 和 [Discussions](https://github.com/antvis/S2/discussions) 列表的问题感兴趣, 可以直接认领并尝试修复 ([贡献指南](https://s2.antv.antgroup.com/manual/contribution))，帮助 S2 变得更好**
